### PR TITLE
Some tests waring fixes

### PR DESCRIPTION
**Pull request by manso92**
Changes to fix some test warnings

image

### CODE REVIEW

**Comment by vnmabus** [comment]
I need more information on the warnings. Do they appear in Windows only? How the proposed solution fixes them?

**Comment by manso92** [comment]
I still haven't been able to pass the tests on windows. This error belongs to the matplotlib library with a connection to gtk. This avoids warning by avoiding the use of gtk.

**Comment by vnmabus** [comment]
So, **WHERE** do you have found the warning? It does not happen in my machine.

**Comment by manso92** [comment]
On ubuntu 18.04 it makes this warning if you use this script

```bash
git clone git@github.com:GAA-UAM/scikit-fda.git
cd scikit-fda
python3 setup.py test 
```

**Pull request closed without merging**
