### PR TITLE
update references and change default method

### PR DESCRIPTION
**Pull request by jdtuck**
The DP method is more accurate than DP2. Also added a reference which was the first journal paper on these methods after the arxiv paper

### CODE REVIEW

**Comment by jdtuck** [comment]
so looks like the tests are based on DP2, so they failed. Though a few install failures which looks like travis couldn't install cffi this round

**Comment by vnmabus** [comment]
Yes, they were based on DP2, and the differences between DP and DP2 were high in some cases. I do not know why `cffi` fails to install now.

**Comment by jdtuck** [comment]
I am looking at cffi now, as its not consistent on the travis builds.

**Comment by jdtuck** [comment]
so cffi has to do with appveyor deployment to PyPI, will fix that here shortly.

**Comment by vnmabus** [comment]
BTW, I was trying to port a change that we made to your code to your package (basically, we made the size of the discretization customizable, and we removed `dp_nbhd.h`). We exposed the discretization size parameter in our API (although I am fairly certain that nobody depends on it, so it could be removed if you do not find it worthwhile).

**Comment by jdtuck** [comment]
I would be interested in porting that back, have it on my to do list and have never done it. It would help balance speed/accuracy easier in the DP

**Comment by jdtuck** [comment]
If you port that back, we can go back to DP2, I am fine with that. Also cffi is fixed

**Pull request merged**
