### PR TITLE
SRSF formula doc fix

### PR DESCRIPTION
**Pull request by ego-thales**
See #530.

*Sorry for the delay*

### CODE REVIEW

**Comment by vnmabus** [comment]
> _Sorry for the delay_

You do not have to apologize. This is open source software, done in our free time, and nobody is entitled to our unpaid labor.

Thank you for the correction in the docs. However, I would say that the Newton notation for the derivative is not very widely used outside of the area of Differential Geometry. Thus, I would add a sentence such as "where $\dot{f}$ is the first derivative of $f$" or something like that. What do you think?

**Comment by ego-thales** [comment]
> I would say that the Newton notation for the derivative is not very widely used outside of the area of Differential Geometry. Thus, I would add a sentence such as "where f˙ is the first derivative of f" or something like that. What do you think?

I agree completely. Personally, I would directly change all dots to apostrophes. I only tried to keep consistency. Let me know, I can update the PR.

**Comment by vnmabus** [comment]
I think that would be great, thank you!

**Comment by ego-thales** [comment]
> I think that would be great, thank you!

There you go :ok_hand:

**Review by vnmabus — APPROVED** [review]
LGTM

**Pull request merged**
